In [1]:
import pandas as pd
import numpy as np
import tqdm

In [2]:
n = 50 #Число цифр в билете
m = 6 #Число вытащенных номеров

In [3]:
all_numbers = pd.Series([x for x in range(1, n)])

# Подсчет для самого минимального билета

In [4]:
intersection_num = []
for i in tqdm.tqdm(range(300000)):
    lotery_sample = set(all_numbers.sample(n=m))
    players_choise = set(all_numbers.sample(n=m))
    intersection_num.append(len(lotery_sample.intersection(players_choise)))

100%|████████████████████████████████████████████████████████████████████████| 300000/300000 [01:08<00:00, 4376.21it/s]

In [5]:
intersection_num_series = pd.Series(intersection_num)

In [6]:
intersection_num_series.mean()

0.7345766666666667

In [7]:
probability = list(intersection_num_series.value_counts()/100000)
probability.append(1/(49*48*47*46*45*44))
keys = [0, 1, 2, 3, 4, 5, 6]
probability_dict = dict(zip(keys, probability))
probability_dict

{0: 1.3083,
 1: 1.23883,
 2: 0.39689,
 3: 0.05287,
 4: 0.00304,
 5: 7e-05,
 6: 9.932116447247939e-11}

In [8]:
#Есть еще вероятность экста шара (только для 5 совпадений)
intersection_extra = []
for i in tqdm.tqdm(range(300000)):
    lotery_sample = set(all_numbers.sample(n=m+1))
    players_choise = set(all_numbers.sample(n=m))
    intersection_extra.append(len(lotery_sample.intersection(players_choise)) == 5)

100%|████████████████████████████████████████████████████████████████████████| 300000/300000 [01:32<00:00, 3257.87it/s]

In [9]:
probability_dict['5+1'] = pd.Series(intersection_extra).mean()

In [10]:
probability_dict

{0: 1.3083,
 1: 1.23883,
 2: 0.39689,
 3: 0.05287,
 4: 0.00304,
 5: 7e-05,
 6: 9.932116447247939e-11,
 '5+1': 5.333333333333333e-05}

In [11]:
player_num = [x for x in range(800000, 2000001, 100000)] #Можно спрогнозировать на истории прироста максимального приза
max_prize = [x for x in range(20000000, 110000001, 10000000)]
price = 300

result = []
for i in player_num:
    prize_total = i*price
    for j in max_prize:
        expectancy = (probability_dict[2]*300 
                      + probability_dict[3]*1500 
                      + probability_dict[4]*prize_total*0.09/(i*probability_dict[4])
                      + probability_dict[5]*prize_total*0.06/(i*probability_dict[5])
                      + probability_dict['5+1']*prize_total*0.06/(i*probability_dict['5+1'])
                      + probability_dict[6]*max(j, prize_total*0.06))
        result.append([i, j, expectancy])

In [12]:
expectancy_df = pd.DataFrame(result, columns=['player_num', 'max_prize', 'expectancy'])
expectancy_df.pivot_table(index='player_num', columns='max_prize', values='expectancy')

max_prize,20000000,30000000,40000000,50000000,60000000,70000000,80000000,90000000,100000000,110000000
player_num,,,,,,,,,,
800000,261.373986,261.374980,261.375973,261.376966,261.377959,261.378952,261.379946,261.380939,261.381932,261.382925
900000,261.373986,261.374980,261.375973,261.376966,261.377959,261.378952,261.379946,261.380939,261.381932,261.382925
1000000,261.373986,261.374980,261.375973,261.376966,261.377959,261.378952,261.379946,261.380939,261.381932,261.382925
1100000,261.373986,261.374980,261.375973,261.376966,261.377959,261.378952,261.379946,261.380939,261.381932,261.382925
1200000,261.374145,261.374980,261.375973,261.376966,261.377959,261.378952,261.379946,261.380939,261.381932,261.382925
1300000,261.374324,261.374980,261.375973,261.376966,261.377959,261.378952,261.379946,261.380939,261.381932,261.382925
1400000,261.374503,261.374980,261.375973,261.376966,261.377959,261.378952,261.379946,261.380939,261.381932,261.382925
1500000,261.374682,261.374980,261.375973,261.376966,261.377959,261.378952,261.379946,261.380939,261.381932,261.382925
1600000,261.374860,261.374980,261.375973,261.376966,261.377959,261.378952,261.379946,261.380939,261.381932,261.382925
1700000,261.375039,261.375039,261.375973,261.376966,261.377959,261.378952,261.379946,261.380939,261.381932,261.382925
1800000,261.375218,261.375218,261.375973,261.376966,261.377959,261.378952,261.379946,261.380939,261.381932,261.382925
1900000,261.375397,261.375397,261.375973,261.376966,261.377959,261.378952,261.379946,261.380939,261.381932,261.382925
2000000,261.375576,261.375576,261.375973,261.376966,261.377959,261.378952,261.379946,261.380939,261.381932,261.382925

# Подсчет при покупке билета с +1 номером

In [13]:
intersection_num = []
for i in tqdm.tqdm(range(300000)):
    lotery_sample = set(all_numbers.sample(n=m))
    players_choise = set(all_numbers.sample(n=m+1))
    intersection_num.append(len(lotery_sample.intersection(players_choise)))
    
intersection_num_series = pd.Series(intersection_num)

probability = list(intersection_num_series.value_counts()/100000)
keys = [0, 1, 2, 3, 4, 5]
probability_dict = dict(zip(keys, probability))
probability_dict[6] = probability_dict[5]/43
probability_dict

100%|████████████████████████████████████████████████████████████████████████| 300000/300000 [01:34<00:00, 3167.35it/s]

{0: 1.28094,
 1: 1.12243,
 2: 0.50434,
 3: 0.08602,
 4: 0.00608,
 5: 0.00019,
 6: 4.418604651162791e-06}

In [14]:
#Есть еще вероятность экста шара (только для 5 совпадений)
intersection_extra = []
for i in tqdm.tqdm(range(300000)):
    lotery_sample = set(all_numbers.sample(n=m))
    players_choise = set(all_numbers.sample(n=m+1))
    intersection_extra.append(len(lotery_sample.intersection(players_choise)) == 5)
    
probability_dict['5+1'] = pd.Series(intersection_extra).mean()

100%|████████████████████████████████████████████████████████████████████████| 300000/300000 [01:29<00:00, 3343.23it/s]

In [15]:
player_num = [x for x in range(800000, 2000001, 100000)] #Можно спрогнозировать на истории прироста максимального приза
max_prize = [x for x in range(20000000, 110000001, 10000000)]
price = 300

result = []
for i in player_num:
    prize_total = i*price
    for j in max_prize:
        expectancy = (probability_dict[2]*300 
                      + probability_dict[3]*1500 
                      + probability_dict[4]*prize_total*0.09/(i*probability_dict[4])
                      + probability_dict[5]*prize_total*0.06/(i*probability_dict[5])
                      + probability_dict['5+1']*prize_total*0.06/(i*probability_dict['5+1'])
                      + probability_dict[6]*max(j, prize_total*0.06))
        result.append([i, j, expectancy])
        
expectancy_df = pd.DataFrame(result, columns=['player_num', 'max_prize', 'expectancy'])
expectancy_df.pivot_table(index='player_num', columns='max_prize', values='expectancy')

max_prize,20000000,30000000,40000000,50000000,60000000,70000000,80000000,90000000,100000000,110000000
player_num,,,,,,,,,,
800000,431.704093,475.890140,520.076186,564.262233,608.448279,652.634326,696.820372,741.006419,785.192465,829.378512
900000,431.704093,475.890140,520.076186,564.262233,608.448279,652.634326,696.820372,741.006419,785.192465,829.378512
1000000,431.704093,475.890140,520.076186,564.262233,608.448279,652.634326,696.820372,741.006419,785.192465,829.378512
1100000,431.704093,475.890140,520.076186,564.262233,608.448279,652.634326,696.820372,741.006419,785.192465,829.378512
1200000,438.773860,475.890140,520.076186,564.262233,608.448279,652.634326,696.820372,741.006419,785.192465,829.378512
1300000,446.727349,475.890140,520.076186,564.262233,608.448279,652.634326,696.820372,741.006419,785.192465,829.378512
1400000,454.680837,475.890140,520.076186,564.262233,608.448279,652.634326,696.820372,741.006419,785.192465,829.378512
1500000,462.634326,475.890140,520.076186,564.262233,608.448279,652.634326,696.820372,741.006419,785.192465,829.378512
1600000,470.587814,475.890140,520.076186,564.262233,608.448279,652.634326,696.820372,741.006419,785.192465,829.378512
1700000,478.541302,478.541302,520.076186,564.262233,608.448279,652.634326,696.820372,741.006419,785.192465,829.378512
1800000,486.494791,486.494791,520.076186,564.262233,608.448279,652.634326,696.820372,741.006419,785.192465,829.378512
1900000,494.448279,494.448279,520.076186,564.262233,608.448279,652.634326,696.820372,741.006419,785.192465,829.378512
2000000,502.401767,502.401767,520.076186,564.262233,608.448279,652.634326,696.820372,741.006419,785.192465,829.378512